# Generated by Django 5.0.2 on 2024-11-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='cantidadpersonas',
            new_name='cantidadhermanos',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='edad',
        ),
        migrations.AddField(
            model_name='reserva',
            name='F_Modificacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='ImagenCarnet',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fechanacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
