# Generated by Django 5.0 on 2024-12-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_reserva_f_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='ImagenCarnet',
            field=models.ImageField(blank=True, null=True, upload_to='carnets/'),
        ),
    ]
